services:
  - type: web
    name: ubhona
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BASE_PATH
        value: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
